version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/mongo 
    networks:
      - app

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONUNBUFFERED: 1    
    depends_on:
      - mongo
    networks:
      - app
    command:
        python3 read_json.py 

networks:
  app:
    driver: bridge
