version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/mongo 
    networks:
      - app

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - app
    command:
      python3 read_json.py
      tail -f /dev/null

networks:
  app:
    driver: bridge
